# docker-compose.yml
name: fitdesk

networks:
  internal: {}

volumes:
  mongo_data: {}

services:
  # --- Mongo (toujours dispo) ---
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_APP_USER: ${MONGO_APP_USER}
      MONGO_APP_PASSWORD: ${MONGO_APP_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo/mongo-init:/docker-entrypoint-initdb.d:ro
    networks: [internal]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # --- Apps + nginx (prod seulement) ---
  nginx:
    profiles: ["prod"]
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/includes:/etc/nginx/includes:ro
    networks: [internal]
    restart: unless-stopped

  mongo_express:
    profiles: ["prod"]
    image: mongo-express:1
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_ADMIN_PASSWORD}
    networks: [internal]
    ports: ["8081:8081"]
    restart: unless-stopped

  api:
    profiles: ["prod"]
    build: ./api
    env_file: .env
    environment:
      NODE_ENV: prod
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}
      DB_CONN_STRING: ${DB_CONN_STRING}
    networks: [internal]
    expose: ["3000"]
    restart: unless-stopped

  frontoffice:
    profiles: ["prod"]
    build: ./frontoffice
    env_file: .env
    networks: [internal]
    expose: ["80"]
    restart: unless-stopped

  backoffice:
    profiles: ["prod"]
    build: ./backoffice
    env_file: .env
    networks: [internal]
    expose: ["80"]
    restart: unless-stopped

  showcase:
    profiles: ["prod"]
    build: ./showcase
    env_file: .env
    networks: [internal]
    expose: ["80"]
    restart: unless-stopped

  mobile:
    profiles: ["prod"]
    build: ./mobile
    env_file: .env
    networks: [internal]
    expose: ["80"]
    restart: unless-stopped
