# srv/docker-compose.prod.yml
name: fitdesk
networks: { internal: {} }
volumes:
  mongo_data: {}
  letsencrypt: {}
  certbot_www: {} 

services:
  mongo:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo/mongo-init:/docker-entrypoint-initdb.d:ro
    networks: [internal]
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certbot_www:/var/www/certbot
      - letsencrypt:/etc/letsencrypt:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/includes:/etc/nginx/includes:ro
    networks: [internal]
    restart: unless-stopped

  mongo_express:
    image: mongo-express:1
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_ADMIN_PASSWORD}
    ports: ["8081:8081"]
    networks: [internal]
    restart: unless-stopped

  api:
    image: fitdesk_api
    env_file: .env
    networks: [internal]
    expose: ["3000"]
    restart: unless-stopped

  frontoffice:
    image: fitdesk_frontoffice
    env_file: .env
    networks: [internal]
    expose: ["80"]
    restart: unless-stopped

  backoffice:
    image: fitdesk_backoffice
    env_file: .env
    networks: [internal]
    expose: ["80"]
    restart: unless-stopped

  showcase:
    image: fitdesk_showcase
    env_file: .env
    networks: [internal]
    expose: ["80"]
    restart: unless-stopped

  mobile:
    image: fitdesk_mobile
    env_file: .env
    networks: [internal]
    expose: ["80"]
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/ccertbot
      - certbot_www:/var/www/certbot
    networks: [internal]